name: shared_dependencies
description: A Flutter package to share dependencies between modules.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  form_validator: ^2.1.1
  lottie: ^2.6.0
  remixicon: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
