name: favorite
description: A module to deal with favorite pokemons.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pokedex_app:
    path: ../../pokedex_app
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
