name: home
description: A package to deal with home page.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  favorite:
    path: ../favorite
  flutter:
    sdk: flutter
  pokedex_app:
    path: ../../pokedex_app
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
