name: auth
description: Authentication Module for Pokedex App.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  flutter:
    sdk: flutter
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0
